### ISSUE TITLE
percona.com - main website

### ISSUE THREAD

**Issue by sindarina** [isvsecwatch/httpstracker#21]
**SSL Server Test Results**
https://www.ssllabs.com/ssltest/analyze.html?d=percona.com (B)

**Cipherscan Results**

```
Target: percona.com:443

prio  ciphersuite           protocols  pfs_keysize
1     DHE-RSA-AES256-SHA    TLSv1      DH,1024bits
2     AES256-SHA            TLSv1
3     DHE-RSA-AES128-SHA    TLSv1      DH,1024bits
4     AES128-SHA            TLSv1
5     RC4-SHA               TLSv1
6     RC4-MD5               TLSv1
7     EDH-RSA-DES-CBC3-SHA  TLSv1      DH,1024bits
8     DES-CBC3-SHA          TLSv1

Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
TLS ticket lifetime hint: None
OCSP stapling: not supported
Client side cipher ordering
```

**Cipherscan Results (Analysis)**

```
percona.com:443 has bad ssl/tls

Things that are bad:
* remove cipher RC4-SHA
* remove cipher RC4-MD5
* remove cipher EDH-RSA-DES-CBC3-SHA

Changes needed to match the intermediate level:
* remove cipher RC4-SHA
* remove cipher RC4-MD5
* remove cipher EDH-RSA-DES-CBC3-SHA
* consider enabling TLSv1.1
* consider enabling TLSv1.2
* consider using DHE of at least 2048bits and ECC of at least 256bits
* consider enabling OCSP Stapling
* enforce server side ordering

Changes needed to match the modern level:
* remove cipher AES256-SHA
* remove cipher AES128-SHA
* remove cipher RC4-SHA
* remove cipher RC4-MD5
* remove cipher EDH-RSA-DES-CBC3-SHA
* remove cipher DES-CBC3-SHA
* disable TLSv1
* consider enabling TLSv1.1
* consider enabling TLSv1.2
* use DHE of at least 2048bits and ECC of at least 256bits
* consider enabling OCSP Stapling
* enforce server side ordering
```

**Verdict**
Sloppy and outdated, basically. It's not used, either; forum signups and logins are done over HTTP, which really shouldn't be happening in this day and age.

**Comment by sindarina** [comment]
Notified via email; info@percona.com, security@percona.com. Poked on Twitter.

**Comment by sindarina** [comment]
Acknowledged on March 30th. No change so far.

```
Target: percona.com:443

prio  ciphersuite           protocols  pfs_keysize
1     DHE-RSA-AES256-SHA    TLSv1      DH,1024bits
2     AES256-SHA            TLSv1
3     DHE-RSA-AES128-SHA    TLSv1      DH,1024bits
4     AES128-SHA            TLSv1
5     RC4-SHA               TLSv1
6     RC4-MD5               TLSv1
7     EDH-RSA-DES-CBC3-SHA  TLSv1      DH,1024bits
8     DES-CBC3-SHA          TLSv1

Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
TLS ticket lifetime hint: None
OCSP stapling: not supported
Client side cipher ordering
```

**Comment by sindarina** [comment]
No change.

```
percona.com:443 has bad ssl/tls

Things that are bad:
* remove cipher RC4-SHA
* remove cipher RC4-MD5
* remove cipher EDH-RSA-DES-CBC3-SHA

Changes needed to match the intermediate level:
* remove cipher RC4-SHA
* remove cipher RC4-MD5
* remove cipher EDH-RSA-DES-CBC3-SHA
* consider enabling TLSv1.1
* consider enabling TLSv1.2
* consider using DHE of at least 2048bits and ECC of at least 256bits
* consider enabling OCSP Stapling
* enforce server side ordering

Changes needed to match the modern level:
* remove cipher AES256-SHA
* remove cipher AES128-SHA
* remove cipher RC4-SHA
* remove cipher RC4-MD5
* remove cipher EDH-RSA-DES-CBC3-SHA
* remove cipher DES-CBC3-SHA
* disable TLSv1
* consider enabling TLSv1.1
* consider enabling TLSv1.2
* use DHE of at least 2048bits and ECC of at least 256bits
* consider enabling OCSP Stapling
* enforce server side ordering
```

**Comment by sindarina** [comment]
No change.

**Comment by sindarina** [comment]
No change. Reminded via email.

**Comment by sindarina** [comment]
No change yet, but was acknowledged on April 28th as something they are working on.

**Comment by sindarina** [comment]
Heard back yesterday, and they've improved their setup by quite a bit;
https://www.ssllabs.com/ssltest/analyze.html?d=percona.com (A+)

**Cipherscan Results**

```
Target: percona.com:443

prio  ciphersuite                  protocols              pfs_keysize
1     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits
2     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits
3     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
4     DHE-RSA-AES256-GCM-SHA384    TLSv1.2                DH,2048bits
5     DHE-RSA-AES256-SHA256        TLSv1.2                DH,2048bits
6     DHE-RSA-AES256-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,2048bits
7     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits
8     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-256,256bits
9     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
10    DHE-RSA-AES128-GCM-SHA256    TLSv1.2                DH,2048bits
11    DHE-RSA-AES128-SHA256        TLSv1.2                DH,2048bits
12    DHE-RSA-AES128-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,2048bits

Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
TLS ticket lifetime hint: 300
OCSP stapling: supported
Client side cipher ordering
```

**Cipherscan Analysis**

```
percona.com:443 has obscure or unknown ssl/tls

Changes needed to match the intermediate level:
* add cipher AES128-SHA
* enforce server side ordering

Changes needed to match the modern level:
* disable TLSv1
* enforce server side ordering
```

The Cipherscan analysis is a bit off, probably because of the cipher order that's presented due to the lack of server-side cipher ordering. That's something that should still be fixed, along with the chain issue, and the lack of session resumption caching.

Nice improvement, though! They went all the way, kudos!

**Comment by Oneiroi** [comment]
As per separate email

```
prio  ciphersuite                  protocols              pfs_keysize
1     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits
2     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits
3     DHE-RSA-AES128-GCM-SHA256    TLSv1.2                DH,2048bits
4     DHE-RSA-AES256-GCM-SHA384    TLSv1.2                DH,2048bits
5     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-256,256bits
6     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
7     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits
8     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits
9     DHE-RSA-AES128-SHA256        TLSv1.2                DH,2048bits
10    DHE-RSA-AES128-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,2048bits
11    DHE-RSA-AES256-SHA256        TLSv1.2                DH,2048bits
12    DHE-RSA-AES256-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,2048bits

Certificate: trusted, 2048 bit, sha256WithRSAEncryption signature
TLS ticket lifetime hint: 300
OCSP stapling: supported
Server side cipher ordering
```
- chain issue has been fixed
- server side ordering has been implemented
- we can not at this time drop TLS1.0 this is mainly due to old client support e.g. Android whereby versions < 4.3 only support TLS1.0 as well as some other older distros still running OpenSSL 0.9.8 (-tls1_1 and -tls1_2 are not valid options in this version)

**Comment by sindarina** [comment]
@Oneiroi: It's still too early to disable TLSv1.0 for a lot of things, and there's no compelling need to do so just yet. So as long as you support TLSv1.2 for modern browsers, you're good to go. Looks great! :-)

Closing ticket as resolved.

**Comment by evgenyfr** [comment]
Hello ,
please help me I am have XP with Internet Explorer 8  ,also other computer INTERNET Explorer 11
when I am try to brothing on https://www.percona.com
no content show , exist error Internet Explorer cannot display the webpage.
what to do ? how to possible  using percona website from Internet Explorer 8 or other computer INTERNET Explorer 11 ?
Regards,
Evgeny

**Comment by Oneiroi** [comment]
@evgenyfr 

As noted in separate email:

---

This does not appear to be a security issue related to percona.com and instead and issue with your operating system,

Windows XP IE8: windows XP is itself end of life, see http://windows.microsoft.com/en-gb/windows/end-support-help for more, and should not be considered by any means a secure platform.

Recent changes to our SSL configuration by way of implementing hardened standards (https://twitter.com/PerconaSecurity/status/598933698340327424) means Windows XP is unsupported this is why you will be seeing no content.

Our hardened SSL configurations which have been deployed are incompatible with Windows XP IE8, IE 11 should be functional however if using Windows 7 or higher.

**Comment by evgenyfr** [comment]
Hello David ,
thanks for fast answer
version of Internet Explorer11 11.0.9600.17501

this is info of my Browser
*You are here: * Home <https://www.ssllabs.com/index.html> > Projects
<https://www.ssllabs.com/projects/index.html> > SSL Client Test
SSL/TLS Capabilities of Your Browser
*User Agent:* Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0)
like Gecko

Other User Agents » <https://www.ssllabs.com/ssltest/clients.html>

&amp;amp;lt;div id=warningBox style="line-height: 145%"&amp;amp;gt;
&amp;amp;lt;b&amp;amp;gt;Without JavaScript, the following tests will not
run:&amp;amp;lt;/b&amp;amp;gt; (1) Accurate protocol support, (2) SSL 3
POODLE vulnerability, (3) mixed content handling, (4) TLS authentication
bug in Apple's products, and (5) the FREAK attack. Please enable JavaScript
for best results. &amp;amp;lt;/ul&amp;amp;gt; &amp;amp;lt;/div&amp;amp;gt;
&amp;amp;lt;br&amp;amp;gt;
 Protocol Support
Your user agent has good protocol support.
Your user agent supports TLS 1.2, which is the best available protocol
version at the moment.
Logjam Vulnerability (Experimental)
Your user agent is not vulnerable.
For more information about the Logjam attack, please go to weakdh.org.
To test manually, click here <https://www.ssllabs.com:10445/>. Your user
agent is not vulnerable if it fails to connect to the site.
FREAK Vulnerability
Your user agent is not vulnerable.
For more information about the FREAK attack, please go to
www.freakattack.com.
To test manually, click here <https://www.ssllabs.com:10444/>. Your user
agent is not vulnerable if it fails to connect to the site.
POODLE Vulnerability
Your user agent is not vulnerable.
For more information about the POODLE attack, please read this blog post
<https://community.qualys.com/blogs/securitylabs/2014/10/15/ssl-3-is-dead-killed-by-the-poodle-attack>
.
SSL 2 Protocol Support
Your user agent supports SSL 2. You should upgrade.
SSL 2 is a very old, obsolete, and insecure version of the SSL protocol.
You can usually disable this protocol version in configuration, but modern
clients don't support it at all. This really means that you should upgrade
your software to a better version.
iOS and OS X TLS Authentication Vulnerability
Please wait, checking if your user agent is vulnerable...
To test manually, click here <https://www.ssllabs.com:10443/>. If your user
agent refuses to connect, you are not vulnerable. This test requires a
connection to the SSL Labs server on port 10443. A strict outbound firewall
might interfere. You should test Safari running on iOS or OS X. Chrome and
Firefox are not vulnerable, even when running on a vulnerable operating
system. *MORE »*
<https://community.qualys.com/blogs/securitylabs/2014/02/24/ssl-labs-testing-for-apples-tls-authentication-bug>
Protocol Features
 &amp;amp;lt;tr class="tableRow"&amp;amp;gt; &amp;amp;lt;td colspan=2
align=left&amp;amp;gt; &amp;amp;lt;span style="color:
#666666"&amp;amp;gt;(*) Without JavaScript, this test reliably detects only
the highest supported protocol.&amp;amp;lt;/span&amp;amp;gt;
&amp;amp;lt;/td&amp;amp;gt; &amp;amp;lt;/tr&amp;amp;gt; ProtocolsTLS 1.2YesTLS
1.1NoTLS 1.0NoSSL 3NoSSL 2No

Cipher Suites (in order of preference)TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c)
128TLS_RSA_WITH_AES_128_CBC_SHA (0x2f) 128TLS_RSA_WITH_AES_256_CBC_SHA256 (
0x3d) 256TLS_RSA_WITH_AES_256_CBC_SHA (0x35) 256TLS_RSA_WITH_RC4_128_SHA (
0x5)   *WEAK*128TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)
112TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
(0x40)   Forward Secrecy2 128TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x32)   Forward
Secrecy2 128TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x6a)   Forward Secrecy2
256TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x38)   Forward Secrecy2
256TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA
(0x13)   Forward Secrecy2 112TLS_RSA_WITH_RC4_128_MD5 (0x4)
*WEAK*128TLS_EMPTY_RENEGOTIATION_INFO_SCSV
(0xff)-(1) When a browser supports SSL 2, its SSL 2-only suites are shown
only on the very first connection to this site. To see the suites, close
all browser windows, then open this exact page directly. Don't refresh. (2)
Cannot be used for Forward Secrecy because they require DSA keys, which are
effectively limited to 1024 bits.

Protocol DetailsServer Name Indication (SNI)YesSecure RenegotiationYesTLS
compressionNoSession ticketsNoOCSP staplingNoSignature algorithms - Elliptic
curves - Next Protocol NegotiationNoApplication Layer Protocol NegotiationNoSSL
2 handshake compatibilityNo
Mixed Content Handling
Mixed ContentImagesPassiveYesCSSActiveYesScriptsActiveYesXMLHttpRequest
ActiveNoWebSocketsActiveNoFramesActiveYes(1) These tests might cause a
mixed content warning in your browser. That's expected.
(2) If you see a failed test, try to reload the page. If the error
persists, please get in touch.

2015-07-22 11:53 GMT+03:00 David Busby <notifications@github.com>:

**Comment by evgenyfr** [comment]
thanks for help ,
separate email sent
Regards,
Evgeny

**Comment by sindarina** [comment]
@evgenyfr If your IE 11 does not work, it's because its configuration has been messed with. The Percona website works just fine with the default settings.

![percona.com in IE 11](https://cloud.githubusercontent.com/assets/6074566/8823766/ca8a5d62-306f-11e5-82bb-431446e7ce03.png)

Compare your own IE 11 settings with what they should be;
https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207

And for crying out loud, stop using IE 8 on XP. Stop using XP even, it's unsupported, and has several known vulnerabilities that will not be patched. It makes you a risk to yourself and the Internet as a whole. Upgrade your OS as soon as possible, and switch to Firefox or Chrome for your browsing in the meantime.

**Comment by evgenyfr** [comment]
thanks
